Fix example line in README.md
the line `setuptools_version = setuptools_version<58` breaks with
```
ERROR: No matching distribution found for setuptools_version<60
```
by which I inferred that I probably wanted `setuptools<60` :)